[package]
name = "beres-pos"
version = "1.0.0"
edition = "2021"
description = "Beres POS - kasir UMKM (Tauri + Svelte)"
authors = ["Beres UMKM"]
license = "MIT"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-updater = "2"
tauri-plugin-shell = "2"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
